//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about_us
    {
        public about_us()
        {
            this.picture = new HashSet<picture>();
        }
    
        public byte id { get; set; }
        public string text { get; set; }
        public string small_text { get; set; }
    
        public virtual ICollection<picture> picture { get; set; }
    }
}
