//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public card()
        {
            this.card_user = new HashSet<card_user>();
            this.order = new HashSet<order>();
        }
    
        public int id { get; set; }
        public Nullable<int> card_num { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string security_code { get; set; }
        public string cardholder_name { get; set; }
        public string cardholder_surname { get; set; }
    
        public virtual ICollection<card_user> card_user { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
