//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public collection()
        {
            this.product = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> coll_year { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
