//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class color
    {
        public color()
        {
            this.color_prod_pivot = new HashSet<color_prod_pivot>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<color_prod_pivot> color_prod_pivot { get; set; }
    }
}
