//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fit
    {
        public fit()
        {
            this.product_features = new HashSet<product_features>();
            this.product_features1 = new HashSet<product_features>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<product_features> product_features { get; set; }
        public virtual ICollection<product_features> product_features1 { get; set; }
    }
}
