//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_info
    {
        public order_info()
        {
            this.order = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string contact_name { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> zip { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<order> order { get; set; }
    }
}
