//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int id { get; set; }
        public string small { get; set; }
        public string medium { get; set; }
        public string big { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<byte> services_id { get; set; }
        public Nullable<byte> about_us_id { get; set; }
        public Nullable<int> staff_id { get; set; }
    
        public virtual about_us about_us { get; set; }
        public virtual product product { get; set; }
        public virtual services services { get; set; }
        public virtual staff staff { get; set; }
    }
}
