//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poll_choices
    {
        public int id { get; set; }
        public string choice_name { get; set; }
        public Nullable<int> poll_id { get; set; }
    
        public virtual poll poll { get; set; }
    }
}
