//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.color_prod_pivot = new HashSet<color_prod_pivot>();
            this.discount = new HashSet<discount>();
            this.order = new HashSet<order>();
            this.picture = new HashSet<picture>();
            this.product_info = new HashSet<product_info>();
            this.product_review = new HashSet<product_review>();
            this.rating = new HashSet<rating>();
            this.size_prod_pivot = new HashSet<size_prod_pivot>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public Nullable<int> collection_id { get; set; }
        public Nullable<int> product_features_id { get; set; }
        public Nullable<byte> sex_id { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<byte> sub_category_id { get; set; }
        public Nullable<int> adder_user { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual ICollection<color_prod_pivot> color_prod_pivot { get; set; }
        public virtual ICollection<discount> discount { get; set; }
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<picture> picture { get; set; }
        public virtual ICollection<product_info> product_info { get; set; }
        public virtual product_features product_features { get; set; }
        public virtual ICollection<product_review> product_review { get; set; }
        public virtual sex_category sex_category { get; set; }
        public virtual sub_category sub_category { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<rating> rating { get; set; }
        public virtual ICollection<size_prod_pivot> size_prod_pivot { get; set; }
    }
}
