//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_features
    {
        public product_features()
        {
            this.product = new HashSet<product>();
        }
    
        public int id { get; set; }
        public Nullable<byte> material_id { get; set; }
        public Nullable<byte> neckline_id { get; set; }
        public Nullable<byte> pattern_id { get; set; }
        public Nullable<byte> sleeve_id { get; set; }
        public Nullable<byte> upper_fit_id { get; set; }
        public Nullable<byte> bottom_fit_id { get; set; }
        public Nullable<byte> pocket_id { get; set; }
        public Nullable<byte> base_id { get; set; }
    
        public virtual @base @base { get; set; }
        public virtual fit fit { get; set; }
        public virtual fit fit1 { get; set; }
        public virtual material material { get; set; }
        public virtual neckline neckline { get; set; }
        public virtual pattern pattern { get; set; }
        public virtual pocket pocket { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual sleeve sleeve { get; set; }
    }
}
