//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sex_category
    {
        public sex_category()
        {
            this.product = new HashSet<product>();
            this.sub_category = new HashSet<sub_category>();
        }
    
        public byte id { get; set; }
        public string sex_name { get; set; }
    
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<sub_category> sub_category { get; set; }
    }
}
