//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class size
    {
        public size()
        {
            this.size_prod_pivot = new HashSet<size_prod_pivot>();
        }
    
        public byte id { get; set; }
        public Nullable<byte> category_id { get; set; }
        public string size_name { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<size_prod_pivot> size_prod_pivot { get; set; }
    }
}
