//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.picture = new HashSet<picture>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<byte> staff_role_id { get; set; }
        public string facebook_adress { get; set; }
        public string twitter_adress { get; set; }
        public string instagram_adress { get; set; }
        public string linkedin_adress { get; set; }
    
        public virtual ICollection<picture> picture { get; set; }
        public virtual staff_role staff_role { get; set; }
        public virtual user user { get; set; }
    }
}
