//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_role
    {
        public staff_role()
        {
            this.staff = new HashSet<staff>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<staff> staff { get; set; }
    }
}
