//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_category
    {
        public sub_category()
        {
            this.product = new HashSet<product>();
        }
    
        public byte id { get; set; }
        public Nullable<byte> sex_id { get; set; }
        public string sub_category_name { get; set; }
        public Nullable<byte> category_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual sex_category sex_category { get; set; }
    }
}
