//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elite_shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.card_user = new HashSet<card_user>();
            this.message = new HashSet<message>();
            this.message1 = new HashSet<message>();
            this.order = new HashSet<order>();
            this.product = new HashSet<product>();
            this.product_review = new HashSet<product_review>();
            this.product_review1 = new HashSet<product_review>();
            this.staff = new HashSet<staff>();
            this.user_role = new HashSet<user_role>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<card_user> card_user { get; set; }
        public virtual ICollection<message> message { get; set; }
        public virtual ICollection<message> message1 { get; set; }
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<product_review> product_review { get; set; }
        public virtual ICollection<product_review> product_review1 { get; set; }
        public virtual ICollection<staff> staff { get; set; }
        public virtual ICollection<user_role> user_role { get; set; }
    }
}
